#!/bin/bash
sudo rm -r out
if [[ ! -d gcc ]]; then
git clone https://github.com/Ruben1863/android_gcc_6.4.1_arm-eabi gcc
fi
mkdir -p out
export KBUILD_BUILD_USER=RuB3N1863
export KBUILD_BUILD_HOST=X5_Pro
export CROSS_COMPILE=${PWD}/gcc/bin/arm-eabi-
export ARCH=arm
export SUBARCH=arm
export TARGET=out
make O=$TARGET ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE x5_pro_defconfig | tee -a Defconfig.log
make O=$TARGET ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE -j$(nproc --all) | tee -a Kernel.log
